language: ruby

rvm:
  - 2.2.2

branches:
  only:
  - master

before_install:
  - gem install bundler

install:
- bundle install

before_script:
- git config --global user.name 'CodyRobot'
- git config --global user.email 'robot4hs@gmail.com'

script:
- bundle exec jekyll build

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch https://$ROBOT_TOKEN@github.com/int64ago/wasm-cn.git . || (git init && git remote add -t gh-pages origin https://$ROBOT_TOKEN@github.com/int64ago/wasm-cn.git)
- rm -rf ./*
- cp -r ../docs/* .
- git add -A .
- git commit -m 'Auto updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
